### ISSUE TITLE
comparison feature calibration issue

### ISSUE THREAD

**Issue by ethanbass** [publiclab/spectral-workbench#325]
I have two calibrated spectra from the same session (i.e. I went back to the same window of spectral work bench after saving one spectrum and saved the next spectrum). The spectra are both calibrated, but when I go to compare them, the one I am trying to overlay is not calibrated. It doesn't matter what the order of operations is (I can pull up either spectrum and try to compare it to the other and the same problem arises).

I am attaching a screenshot of two spectra superimposed, where one is not showing up as calibrated. Perhaps it has something to do with the new operations function. I can only guess that the comparison function may not be accessing the "snapshot" where the calibration information has been saved.

<img width="1021" alt="screen shot 2016-02-11 at 4 49 54 pm" src="https://cloud.githubusercontent.com/assets/15876283/12993404/91de9666-d0df-11e5-9b8e-8ba353826ab7.png">

**Comment by jywarren** [comment]
Thanks, Ethan - can you give me spectrum IDs to compare? Thanks!

**Comment by jywarren** [comment]
Reproduced and confirmed for https://spectralworkbench.org/spectrums/71375 and https://spectralworkbench.org/spectrums/71376 -- will look at this tomorrow morning. Thanks again!

**Comment by jywarren** [comment]
`calibrate` operations weren't properly storing a snapshot; this is resolved but you have to delete and regenerate the operations. I've tested this on forks: https://spectralworkbench.org/spectrums/71811 and https://spectralworkbench.org/spectrums/71810

However, now that I've forked your spectra, you won't be able to modify them. You can either fork your own, or if you like I can delete my forks.

Anyhow, this bug is resolved in v2.1.9, now live! Thanks, Ethan!
